### PR TITLE
Symbols: add more Latin characters according to Unicode Charts.

### PR DESCRIPTION
**Pull request by wzy9607**
Some characters in Unicode Latin blocks are difficult to classify so aren't added.

### CODE REVIEW

**Comment by lotem** [comment]
This is an exciting pull request.
Sth + `da` isn't found in existing code for symbols. There's sth+ `d` where sth being also pinyin initials.
Personally I prefer `/A`, more intuitive and easier to type. What made you change your mind?

**Comment by lotem** [comment]
To use `/A` for capital letters, you also need to change this pattern in your schema:
https://github.com/rime/rime-luna-pinyin/blob/master/luna_pinyin.schema.yaml#L109
to `'^/([0-9]0?|[A-Za-z]+)$'`.
For now this has to be done in every .schema.yaml file that imports `symbols`.
How about we add a comment in `symbols.yaml`:
```yaml
# patch your Rime schema to enable /x symbols:
# patch:
#   recognizer/patterns/punct: '^/([0-9]0?|[A-Za-z]+)$'

```
I soon will create a solution for sharing code snippets in the rime library.

**Comment by wzy9607** [comment]
The comment is added. And I also provided an example file.

**Comment by lotem** [comment]
Thanks. It works perfectly.

**Pull request merged**
